"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 17:59:03.932355
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('proveedor', sa.String(length=40), nullable=False),
    sa.Column('numero', sa.String(length=60), nullable=False),
    sa.Column('recibido', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('semaforo', sa.String(length=6), nullable=True),
    sa.Column('pedido', sa.String(length=40), nullable=True),
    sa.Column('numero_registro_siddex', sa.String(length=20), nullable=True),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor', 'tipo', 'numero', name='uq_documento_proveedor_tipo_numero')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_proveedor'), ['proveedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_recibido'), ['recibido'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_semaforo'), ['semaforo'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_sha256'), ['sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_documentos_tipo'), ['tipo'], unique=False)

    op.create_table('encargos',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('proveedor', sa.String(length=80), nullable=False),
    sa.Column('articulo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=10), nullable=False),
    sa.Column('quien', sa.String(length=40), nullable=False),
    sa.Column('origen', sa.String(length=12), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('pedido', sa.String(length=40), nullable=True),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encargos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encargos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_encargos_fecha'), ['fecha'], unique=False)

    op.create_table('eventos',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('documento_id', sa.String(length=12), nullable=True),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_documento_id'), ['documento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_tipo'), ['tipo'], unique=False)

    op.create_table('pedidos',
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('proveedor', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('relacion', sa.String(length=20), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=True),
    sa.Column('numero_siddex', sa.String(length=40), nullable=True),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('numero')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_proveedor'), ['proveedor'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_proveedor'))

    op.drop_table('pedidos')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_tipo'))
        batch_op.drop_index(batch_op.f('ix_eventos_fecha'))
        batch_op.drop_index(batch_op.f('ix_eventos_documento_id'))

    op.drop_table('eventos')
    with op.batch_alter_table('encargos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encargos_fecha'))
        batch_op.drop_index(batch_op.f('ix_encargos_estado'))

    op.drop_table('encargos')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_tipo'))
        batch_op.drop_index(batch_op.f('ix_documentos_sha256'))
        batch_op.drop_index(batch_op.f('ix_documentos_semaforo'))
        batch_op.drop_index(batch_op.f('ix_documentos_recibido'))
        batch_op.drop_index(batch_op.f('ix_documentos_proveedor'))
        batch_op.drop_index(batch_op.f('ix_documentos_estado'))

    op.drop_table('documentos')
    # ### end Alembic commands ###
