"""ejecuciones y ejecucion_id en eventos

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 10:06:33.649911
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejecuciones',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('tarea', sa.String(length=40), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('n_documentos', sa.Integer(), nullable=False),
    sa.Column('n_nuevos', sa.Integer(), nullable=False),
    sa.Column('n_duplicados', sa.Integer(), nullable=False),
    sa.Column('n_no_procesables', sa.Integer(), nullable=False),
    sa.Column('n_errores', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ejecuciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ejecuciones_inicio'), ['inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejecuciones_tarea'), ['tarea'], unique=False)

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ejecucion_id', sa.String(length=12), nullable=True))
        batch_op.create_index(batch_op.f('ix_eventos_ejecucion_id'), ['ejecucion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_ejecucion_id'))
        batch_op.drop_column('ejecucion_id')

    with op.batch_alter_table('ejecuciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejecuciones_tarea'))
        batch_op.drop_index(batch_op.f('ix_ejecuciones_inicio'))

    op.drop_table('ejecuciones')
    # ### end Alembic commands ###
